###`Q1:` Join Tuples if similar initial element
While working with Python tuples, we can have a problem in which we need to perform concatenation of records from the similarity of initial element. This problem can have applications in data domains such as Data Science.

For eg.
```
Input  : test_list = [(5, 6), (5, 7), (5, 8), (6, 10), (7, 13)]
Output : [(5, 6, 7, 8), (6, 10), (7, 13)]
```

In [ ]:
# write your code here

###`Q2:` Multiply Adjacent elements (both side) and take sum of right and lest side multiplication result.


For eg.
```
The original tuple : (1, 5, 7, 8, 10)
Resultant tuple after multiplication :

(1*5, 1*5+5*7, 7*5 + 7*8, 8*7 + 8*10, 10*8) -> (5, 40, 91, 136, 80)

output-(5, 40, 91, 136, 80)
```

In [ ]:
# write your code here
tup = (1, 5, 7, 8, 10)
res = []

for i in range(len(tup)):
    if i == 0:
        res.append(tup[i] * tup[i + 1])
    elif i == len(tup) - 1:
        res.append(tup[i] * tup[i - 1])
    else:
        res.append(tup[i] * tup[i - 1] + tup[i] * tup[i + 1])

# Convert result to tuple
print(tuple(res))

(5, 40, 91, 136, 80)

###`Q3`: Check is tuples are same or not?
Two tuples would be same if both tuples have same element at same index
```
t1 = (1,2,3,0)
t2 = (0,1,2,3)

t1 and t2 are not same
```

In [ ]:
# write your code here
t1 = (1,2,3,0)
t2 = (0,1,2,3)

if t1 == t2 :
  print('t1 and t2 are same')
else:
  print('t1 and t2 are not same')

t1 and t2 are not same

###`Q4`: Count no of tuples, list and set from a list
```
list1 = [{'hi', 'bye'},{'Geeks', 'forGeeks'},('a', 'b'),['hi', 'bye'],['a', 'b']]

```
`Output:`

```
List-2
Set-2
Tuples-1
```

In [ ]:
# write your code here
list1 = [{'hi', 'bye'},{'Geeks', 'forGeeks'},('a', 'b'),['hi', 'bye'],['a', 'b']]
Set = 0
List = 0
Tuples = 0


for i in list1:
  if type(i) == set:
    Set = Set +1
  elif type(i) == list:
    List = List +1
  elif type(i) == tuple:
    Tuples = Tuples +1


print('List','-',List)

print('Set','-',Set)


print('Tuples','-',Tuples)

List - 2
Set - 2
Tuples - 1

({'bye', 'hi'}, {'Geeks', 'forGeeks'}, ('a', 'b'), ['hi', 'bye'], ['a', 'b'])

###`Q5`: Shortlist Students for a Job role
Ask user to input students record and store in tuples for each record. Then Ask user to input three things he wants in the candidate- Primary Skill, Higher Education, Year of Graduation.

Show every students record in form of tuples if matches all required criteria.

It is assumed that there will be only one primry skill.

If no such candidate found, print `No such candidate`

`Input:`
```
Enter No of records- 2
Enter Details of student-1
Enter Student name- Manohar
Enter Higher Education- B.Tech
Enter Primary Skill- Python
Enter Year of Graduation- 2022
Enter Details of student-2
Enter Student name- Ponian
Enter Higher Education- B.Sc.
Enter Primary Skill- C++
Enter Year of Graduation- 2020

Enter Job Role Requirement
Enter Skill- Python
Enter Higher Education- B.Tech
Enter Year of Graduation- 2022
```

`Output`
```
('Manohar', 'B.tech', 'Python', '2022')
```

In [ ]:
# write your code here

flag = int(input('enter a number of candinate- '))
res = []

while flag > 0:
  num = int(input('Enter No of records- '))
  no_student = int(input('Enter Details of student- '))
  name = input('Enter Student name- ')
  education = input('Enter Higher Education- ')
  skills = input('Enter Primary Skill-')
  year = int(input('Enter Year of Graduation-'))
  records = (name , education , skills , year)
  flag = flag - 1
  res.append(records)
  records = ()



result = tuple(res)

print('Enter Job Role Requirement')

skil = input('enter a skils- ')
edu = input('Enter Higher Education-')
yr = int(input('Enter Year of Graduation-'))


flags = 0


for i in result:
  for j in i:
    if j == skil:
      flags = flags +1
    elif j == edu :
      flags = flags + 1
    elif j == yr :
      flags = flags + 1

  if flags == 3:
    print(i)
  else:
    flags = 0

enter a number of candinate- 2
Enter No of records- 1
Enter Details of student- 1
Enter Student name- Mayank
Enter Higher Education- BCA
Enter Primary Skill-python
Enter Year of Graduation-2025
Enter No of records- 2
Enter Details of student- 2
Enter Student name- deepak
Enter Higher Education- BCA
Enter Primary Skill-c++
Enter Year of Graduation-2025
Enter Job Role Requirement
enter a skils- python
Enter Higher Education-BCA
Enter Year of Graduation-2025
('Mayank ', 'BCA', 'python', 2025)

# Set

###`Q1:` Write a program to find set of common elements in three lists using sets.
```
Input : ar1 = [1, 5, 10, 20, 40, 80]
        ar2 = [6, 7, 20, 80, 100]
        ar3 = [3, 4, 15, 20, 30, 70, 80, 120]

Output : [80, 20]
```

In [ ]:
# write your code here
ar1 = [1, 5, 10, 20, 40, 80]
ar2 = [6, 7, 20, 80, 100]
ar3 = [3, 4, 15, 20, 30, 70, 80, 120]

#approch-1

result = []
for i in ar1:
  for j in ar2:
    if i==j:
      for k in ar3:
        if j == k:
          result.append(k)
print(result)

#approch-2

set1 = set(ar1)
set2 = set(ar2)
set3 = set(ar3)

comoan= set1 & set2 & set3

print(list(comoan))

[20, 80]
[80, 20]

###`Q2:` Write a program to count unique number of vowels using sets in a given string. Lowercase and upercase vowels will be taken as different.

`Input:`
```
Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
```
`Output:`
```
No of unique vowels-6
```

In [ ]:
# write your code here
Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
vowels = {'A','E','I','O','U','a','e','i','o','u'}


s =set()


for i in Str1:
  if i in vowels:
    s.add(i)

print('No of unique vowels =',len(s))

No of unique vowels = 6

### `Q3:` Write a program to Check if a given string is binary string of or not.

A string is said to be binary if it's consists of only two unique characters.

Take string input from user.

```
Input: str = "01010101010"
Output: Yes

Input: str = "1222211"
Output: Yes

Input: str = "Campusx"
Output: No
```

In [ ]:
# write your code here
str1 = "01010101010C"
char = set('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz')
s =set()

#1st approch

for i in str1:
  if i in char:
    s.add(i)
    break
  else:
    s.add(i)

if len(s) == 2:
  print('yes')

else:
  print('NO')

#2nd approch

s2 = set(str1)
if len(s2) == 2:
  print('yes')
else:
  print('no')

NO
no

### `Q4`: find union of n arrays.

**Example 1:**

Input:
```bash
[[1, 2, 2, 4, 3, 6],
 [5, 1, 3, 4],
 [9, 5, 7, 1],
 [2, 4, 1, 3]]
```

Output:

```bash
[1, 2, 3, 4, 5, 6, 7, 9]
```

In [ ]:
# write your code here
s = [[1, 2, 2, 4, 3, 6],
 [5, 1, 3, 4],
 [9, 5, 7, 1],
 [2, 4, 1, 3]]
s1 = set()

for i in s:
 for j in i:
  s1.add(j)

print(s1)

{1, 2, 3, 4, 5, 6, 7, 9}

### `Q5`: Intersection of two lists. Intersection of two list means we need to take all those elements which are common to both of the initial lists and store them into another list. Only use using **list-comprehension**.

**Example 1:**

Input:
```bash
lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}
```

Output:
```bash
[9, 10, 4, 5]
```

**Example 2:**

Input:
```bash
lst1 = {4, 9, 1, 17, 11, 26, 28, 54, 69}
lst2 = {9, 9, 74, 21, 45, 11, 63, 28, 26}
```

Output:
```bash
[9, 11, 26, 28]
```

In [ ]:
# write your code here
lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}

l = [i for i in lst1 if i in lst2]
print(set(l))

{9, 10, 4, 5}

# Dictionary

### `Q1`: Key with maximum unique values

Given a dictionary with values list, extract key whose value has most unique values.

**Example 1:**

Input:

```bash
test_dict = {"CampusX" : [5, 7, 9, 4, 0], "is" : [6, 7, 4, 3, 3], "Best" : [9, 9, 6, 5, 5]}
```

Output:
```bash
CampusX
```

**Example 2:**

Input:
```bash
test_dict = {"CampusX" : [5, 7, 7, 7, 7], "is" : [6, 7, 7, 7], "Best" : [9, 9, 6, 5, 5]}
```

Output:
```bash
Best
```

In [ ]:
test_dict =  {"CampusX" : [5, 7, 7, 7, 7], "is" : [6, 7, 7, 7], "Best" : [9, 9, 6, 5, 5]}
l = []
for i in test_dict:
  s = set()
  for j in test_dict[i]:
    s.add(j)
  l.append(len(s))
l

maxs = max(l)
indexs = l.index(maxs)
l1 = []
for i in test_dict.keys():
 l1.append(i)

print(l1[indexs])

Best

### `Q2`: Replace words from Dictionary. Given String, replace it’s words from lookup dictionary.

**Example 1:**

Input:

```bash
test_str = 'CampusX best for DS students.'
repl_dict = {"best" : "is the best channel", "DS" : "Data-Science"}
```

Output:

```bash
CampusX is the best channel for Data-Science students.
```

**Example 2:**

Input:
```bash
test_str = 'CampusX best for DS students.'
repl_dict = {"good" : "is the best channel", "ds" : "Data-Science"}
```

Output:
```bash
CampusX best for DS students.
```

In [85]:
t = 'CampusX best for DS students.'
r = {"best" : "is the best channel", "DS" : "Data-Science"}
l = t.split()
l1 =[]
key = r.keys()

# for i in l :
#   for j in r.keys():
#    if i == j:
#     l1.append(r[j])
#     break
#    elif i in l1 :
#      continue
#    elif i in key:
#     continue
#    else:
#       l1.append(i)


# l1


for i in l1:
  print(i,end=" ")


t = 'CampusX best for DS students.'
r = {"best": "is the best channel", "DS": "Data-Science"}

l = t.split()
l1 = []

for i in l:
    if i in r:
        l1.append(r[i])
    else:
        l1.append(i)

print(' '.join(l1))

CampusX is the best channel for Data-Science students.

### `Q3`: Convert List to List of dictionaries. Given list values and keys list, convert these values to key value pairs in form of list of dictionaries.

**Example 1:**

Input:
```bash
test_list = ["DataScience", 3, "is", 8]
key_list = ["name", "id"]
```

Output:

```bash
[{'name': 'DataScience', 'id': 3}, {'name': 'is', 'id': 8}]
```

**Example 2:**

Input:
```bash
test_list = ["CampusX", 10]
key_list = ["name", "id"]
```

Output:

```bash
[{'name': 'CampusX', 'id': 10}]
```

In [26]:
test_list = ["DataScience", 3, "is", 8]
key_list = ["name", "id"]

output = []
for i in range(0, len(test_list), len(key_list)):
    temp = {}
    for j in range(len(key_list)):
        temp[key_list[j]] = test_list[i + j]
    output.append(temp)

print(output)

[{'name': 'DataScience', 'id': 3}, {'name': 'is', 'id': 8}]

### `Q4`: Convert a list of Tuples into Dictionary.

**Example 1:**

Input:
```bash
[("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
```

Output:
```bash
{'akash': [10], 'gaurav': [12], 'anand': [14], 'suraj': [20], 'akhil': [25], 'ashish': [30]}
```

**Example 2:**

Input:
```bash
[('A', 1), ('B', 2), ('C', 3)]
```

Output:
```bash
{'A': [1], 'B': [2], 'C': [3]}
```

In [65]:
t = [("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
d = {}


for i in range(len(t)):
  d[t[i][0]]=[t[i][1]]


print(d)

output = {k: [v] for k,v in t}
print(output)

{'akash': [10], 'gaurav': [12], 'anand': [14], 'suraj': [20], 'akhil': [25], 'ashish': [30]}
{'akash': [10], 'gaurav': [12], 'anand': [14], 'suraj': [20], 'akhil': [25], 'ashish': [30]}

### `Q5`: Sort Dictionary key and values List.

**Example 1:**

Input:

```bash
{'c': [3], 'b': [12, 10], 'a': [19, 4]}
```

Output:

```bash
{'a': [4, 19], 'b': [10, 12], 'c': [3]}
```

**Example 2:**

Input:

```bash
{'c': [10, 34, 3]}
```

Output:

```bash
{'c': [3, 10, 34]}
```

In [84]:
test_dict = {'c': [3], 'b': [12, 10], 'a': [19, 4]}

# Step 1: Sort keys using sorted()
# Step 2: Sort each value list using sorted()

res = {k: sorted(test_dict[k]) for k in sorted(test_dict)}

print(res)

{'a': [4, 19], 'b': [10, 12], 'c': [3]}